FROM python:3.12-slim

COPY run_bot.py ../BGEvr/run_bot.py
COPY requirements.txt ../BGEvr/requirements.txt
COPY .env C:/Users/райан гослинг/Documents\GitHub/Yellow_Team_Project/BGEvr/.env

RUN pip install -r requirements.txt